[project]
name = "jax-tinkering"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.8.1",
    "jaxtyping>=0.3.3",
    "matplotlib>=3.10.7",
    "scikit-learn>=1.7.2",
    "scikit-learn-stubs>=0.0.3",
]
